import { ChallengeData } from './types';

const challengeDatas: { [key: number]: ChallengeData } = {
  1021:  { title: '회전하는 큐', level: 'Silver IV', tags: ['Double-ended queue'] },
  1094:  { title: '막대기', level: 'Silver V', tags: ['Implementation'] },
  1107:  { title: '리모컨', level: 'Gold V', tags: ['Brute-force search'] },
  1389:  { title: '케빈 베이컨의 6단계 법칙', level: 'Silver I', tags: ['BFS', 'Graph theory'] },
  1476:  { title: '날짜 계산', level: 'Silver V', tags: ['Implementation'] },
  1541:  { title: '잃어버린 괄호', level: 'Silver II', tags: ['Greedy algorithm'] },
  1654:  { title: '랜선 자르기', level: 'Silver III', tags: ['Binary search'] },
  1676:  { title: '팩토리얼 0의 개수', level: 'Silver III', tags: ['Mathematics'] },
  1717:  { title: '집합의 표현', level: 'Gold IV', tags: ['Disjoint set'] },
  1964:  { title: '오각형, 오각형, 오각형…', level: 'Bronze III', tags: ['Mathematics'] },
  1992:  { title: '쿼드 트리', level: 'Silver I', tags: ['Divide and conquer', 'Recursion'] },
  2010:  { title: '플러그', level: 'Bronze III', tags: ['Mathematics'] },
  2580:  { title: '스도쿠', level: 'Gold IV', tags: ['Backtracking'] },
  2935:  { title: '소음', level: 'Bronze III', tags: ['Implementation'] },
  5355:  { title: '화성 수학', level: 'Bronze II', tags: ['Implementation'] },
  5430:  { title: 'AC', level: 'Silver II', tags: ['Double-ended queue'] },
  5525:  { title: 'IOIOI', level: 'Silver II', tags: ['Implementation'] },
  5717:  { title: '상근이의 친구들', level: 'Bronze III', tags: ['Implementation'] },
  6064:  { title: '카잉 달력', level: 'Silver I', tags: ['Mathematics'] },
  7569:  { title: '토마토', level: 'Silver I', tags: ['BFS'] },
  7662:  { title: '이중 우선순위 큐', level: 'Gold V', tags: ['Tree'] },
  8320:  { title: '직사각형을 만드는 방법', level: 'Bronze III', tags: ['Mathematics'] },
  9205:  { title: '맥주 마시면서 걸어가기', level: 'Silver I', tags: ['DFS', 'Graph theory'] },
  9375:  { title: '패션왕 신해빈', level: 'Silver III', tags: ['Hash table'] },
  9465:  { title: '스티커', level: 'Silver II', tags: ['Dynamic programming'] },
  9663:  { title: 'N-Queen', level: 'Gold V', tags: ['Backtracking'] },
  10026: { title: '적록색약', level: 'Gold V', tags: ['DFS', 'Recursion'] },
  11047: { title: '동전 0', level: 'Silver I', tags: ['Greedy algorithm'] },
  11286: { title: '절댓값 힙', level: 'Silver I', tags: ['Priority queue'] },
  11399: { title: 'ATM', level: 'Silver III', tags: ['Greedy algorithm', 'Sorting'] },
  11403: { title: '경로 찾기', level: 'Silver I', tags: ['DFS', 'Graph theory'] },
  11536: { title: '줄 세우기', level: 'Silver V', tags: ['Implementation'] },
  11816: { title: '8진수, 10진수, 16진수', level: 'Bronze I', tags: ['Implementation'] },
  14425: { title: '문자열 집합', level: 'Silver III', tags: ['Hash set'] },
  14500: { title: '테트로미노', level: 'Gold V', tags: ['Brute-force search'] },
  17219: { title: '비밀번호 찾기', level: 'Silver IV', tags: ['Hash table'] },
  17626: { title: 'Four Squares', level: 'Silver V', tags: ['Dynamic programming'] },
  18870: { title: '좌표 압축', level: 'Silver II', tags: ['Coordinate compression', 'Sorting'] }
};

export default challengeDatas;